[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaCustom.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "straight-bar"
seven = "bend-serifed-crossbar"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed-split"
capital-a = "round-top-serifless"
capital-b = "more-asymmetric-unilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "open-serifless"
capital-q = "open-swash"
capital-r = "standing-open-serifless"
capital-t = "serifless"
capital-v = "straight-serifless"
capital-w = "rounded-vertical-sides-flat-top-motion-serifed"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifed-with-horizontal-crossbar"
a = "single-storey-earless-rounded-tailed"
b = "toothless-rounded-serifed"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "double-storey"
h = "tailed-serifless"
i = "flat-tailed"
j = "flat-hook-serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "cursive-serifed"
w = "straight-serifless"
x = "semi-chancery-straight-serifless"
y = "curly-motion-serifed"
z = "curly-bottom-serifed"
long-s = "bent-hook-tailed"
lower-eth = "straight-bar"
capital-delta = "straight"
lower-delta = "flat-top"
lower-lambda = "curly-tailed-turn"
lower-pi = "tailed"
lower-chi = "semi-chancery-curly-serifless"
cyrl-ef = "serifless"
tittle = "round"
punctuation-dot = "round"
braille-dot = "round"
tilde = "high"
asterisk = "turn-penta-low"
underscore = "high"
caret = "low"
ascii-grave = "straight"
ascii-single-quote = "raised-comma"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted-tall"
ampersand = "upper-open"
at = "fourfold"
dollar = "interrupted"
percent = "rings-segmented-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "low"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "dlig"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700