[start]
visual-home = "cgi-bin:chabookmark?action=view"

[buffer]
images = true

[display]
image-mode = "kitty"

[page]
'C-h' = 'pager.loadSubmit("about:chawan")'
'C-k' = '() => pager.load("ddg:")'

[[siteconf]]
url = 'https://merveilles\.town/.*'
cookie = "save"
scripting = "app"

[[siteconf]]
url = 'http://localhost:8384/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://meta\.sr\.ht/.*'
cookie = 'save'
scripting = 'app'


[[siteconf]]
url = 'https://git\.sr\.ht/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://meta\.sr\.ht/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
host = '(.*\.)?sr\.ht' # either 'something.sr.ht' or 'sr.ht'          
# url = 'https://sr\.ht/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://bakabt\.me/.*'
scripting = 'app'
cookie = 'save'

[[siteconf]]
url = 'https://compudanzas\.itch\.io/.*'
scripting = 'app'

[[siteconf]]
url = 'https://stackoverflow\.com/.*'
cookie = true
scripting = true

[[siteconf]]
url = 'https://tex\.stackexchange\.com/.*'
cookie = true
scripting = true
