# fucking boring
# font_family IosevkaTermNerdFont
font_family MonaspiceNerdFont 
update_check_interval 0

enable_audio_bell no
# minecraft
# font_family GohuFont11NerdFont

background_opacity 0.8

kitty_mod ctrl+shift
font_family Hack Regular
# font_family      monospace
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# enabled_layouts splits:split_axis=horizontal
# enabled_layouts tall:bias=51;full_size=1;mirrored=false                                
enabled_layouts splits
map ctrl+a>s launch --location=hsplit --cwd=current
map ctrl+a>v launch --location=vsplit --cwd=current
map ctrl+a>l next_layout
map ctrl+a>c new_tab_with_cwd
map ctrl+a>enter new_window_with_cwd
map ctrl+a>g>t next_tab
map ctrl+a>g>shift+t previous_tab
map ctrl+a>n next_tab
map ctrl+a>shift+n previous_tab
map ctrl+a>p previous_tab

map ctrl+a>k neighboring_window top
map ctrl+a>j neighboring_window bottom
map ctrl+a>h neighboring_window left
map ctrl+a>l neighboring_window right 
# map ctrl+k neighboring_window top
# map ctrl+j neighboring_window bottom
# map ctrl+h neighboring_window left
# map ctrl+l neighboring_window right 

# map ctrl+shift+a>k move_window_to_top
# map ctrl+shift+a>j move_window_to_bottom
# map ctrl+shift+a>h move_window_backward
# map ctrl+shift+a>l move_window_forward

map --new-mode rsz --on-unknown end ctrl+a>=
map --mode rsz h resize_window wider 10
map --mode rsz l resize_window narrower 10
map --mode rsz k resize_window taller 10
map --mode rsz j resize_window shorter 10
map --mode rsz = combine : resize_window reset : end
map --mode rsz esc pop_keyboard_mode

# map ctrl+a>+ combine : resize_window wider 10 : resize_window taller 10
# map ctrl+a>- combine : resize_window narrower 10 : resize_window shorter 10
# map ctrl+a>_ resize_window taller 10
# map ctrl+a>^ resize_window shorter 10
# map ctrl+a>= resize_window reset
map ctrl+shift+a>k layout_action move_to_screen_edge top
map ctrl+shift+a>j layout_action move_to_screen_edge bottom
map ctrl+shift+a>h layout_action move_to_screen_edge left
map ctrl+shift+a>l layout_action move_to_screen_edge right

map ctrl+a>] next_window
map ctrl+a>[ previous_window

map ctrl+a>r load_config_file
map ctrl+shift+a>r debug_config 

map ctrl+a+] next_window
map ctrl+a+[ previous_window

map ctrl+a>! detach_window new-tab
map ctrl+a>? detach_window ask

map ctrl+a>f1 show_kitty_doc conf

map alt+v kitten kitty_grab/grab.py

map ctrl+shift+u scroll_page_up
map ctrl+shift+d scroll_page_down
